### ISSUE TITLE
?

### ISSUE THREAD

**Issue by conradkolb** [fadookie/hal9000#1]
How do I use the HAL 9000 voice?

**Comment by fadookie** [comment]
This is just a simple example of using the chrome text-to-speech and speech-to-text services - it doesn't actually sound like HAL 9000, and `x-webkit-speech` is apparently now deprecated so it no longer works. Sorry.

**Comment by conradkolb** [comment]
Do you know if there is anyway to get a HAL 9000 voice?

**Comment by fadookie** [comment]
@conradkolb I'm sorry Dave, I'm afraid I can't do that.
